package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/thejayhaykid/vuer/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Band)
// DB Table: Plural (bands)
// Resource: Plural (Bands)
// Path: Plural (/bands)
// View Template Folder: Plural (/templates/bands/)

// BandsResource is the resource for the Band model
type BandsResource struct {
	buffalo.Resource
}

// List gets all Bands. This function is mapped to the path
// GET /bands
func (v BandsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	bands := &models.Bands{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Bands from the DB
	if err := q.All(bands); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, bands))
}

// Show gets the data for one Band. This function is mapped to
// the path GET /bands/{band_id}
func (v BandsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Band
	band := &models.Band{}

	// To find the Band the parameter band_id is used.
	if err := tx.Find(band, c.Param("band_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, band))
}

// New renders the form for creating a new Band.
// This function is mapped to the path GET /bands/new
func (v BandsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Band{}))
}

// Create adds a Band to the DB. This function is mapped to the
// path POST /bands
func (v BandsResource) Create(c buffalo.Context) error {
	// Allocate an empty Band
	band := &models.Band{}

	// Bind band to the html form elements
	if err := c.Bind(band); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(band)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, band))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "band.created.success")
	// and redirect to the bands index page
	return c.Render(201, r.Auto(c, band))
}

// Edit renders a edit form for a Band. This function is
// mapped to the path GET /bands/{band_id}/edit
func (v BandsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Band
	band := &models.Band{}

	if err := tx.Find(band, c.Param("band_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, band))
}

// Update changes a Band in the DB. This function is mapped to
// the path PUT /bands/{band_id}
func (v BandsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Band
	band := &models.Band{}

	if err := tx.Find(band, c.Param("band_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Band to the html form elements
	if err := c.Bind(band); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(band)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, band))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "band.updated.success")
	// and redirect to the bands index page
	return c.Render(200, r.Auto(c, band))
}

// Destroy deletes a Band from the DB. This function is mapped
// to the path DELETE /bands/{band_id}
func (v BandsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Band
	band := &models.Band{}

	// To find the Band the parameter band_id is used.
	if err := tx.Find(band, c.Param("band_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(band); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "band.destroyed.success")
	// Redirect to the bands index page
	return c.Render(200, r.Auto(c, band))
}
